name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push backend-service
        run: |
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-service:${{ env.IMAGE_TAG }} ./backend-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-service:${{ env.IMAGE_TAG }}

      - name: Build and Push frontend
        run: |
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ env.IMAGE_TAG }} ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ env.IMAGE_TAG }}

      - name: Build and Push aiService
        run: |
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/aiservice:${{ env.IMAGE_TAG }} ./aiService
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aiservice:${{ env.IMAGE_TAG }}
